version: "3.7"

services:
  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki:/etc/loki
      - ./loki/wal:/wal
      - ./loki/data:/loki
    restart: unless-stopped
    networks:
      - logging

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail.yaml
      - ./logs/app.log:/var/log/app.log
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - logging

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - logging

volumes:
  grafana-storage:

networks:
  logging:
    driver: bridge

